global using Advent_of_Code;
global using AwesomeAssertions;
global using NUnit.Framework;
global using NUnit.Framework.Interfaces;
global using NUnit.Framework.Internal;
global using NUnit.Framework.Internal.Builders;
global using Qowaiv;
global using SmartAss;
global using SmartAss.Collections;
global using SmartAss.Diagnostics;
global using SmartAss.Expressions;
global using SmartAss.Maps;
global using SmartAss.Navigation;
global using SmartAss.Numerics;
global using SmartAss.Pairings;
global using SmartAss.Parsing;
global using SmartAss.Syntax;
global using SmartAss.Trees;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Diagnostics.Contracts;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Text.RegularExpressions;
global using static System.Linq.Enumerable;
global using CategoryAttribute = Advent_of_Code.CategoryAttribute;
global using CharGrid = SmartAss.Collections.Grid<char>;
global using Int = System.Numerics.BigInteger;
global using Int32Range = SmartAss.Numerics.NumericRange<int>;
global using Int32Ranges = SmartAss.Numerics.NumericRanges<int>;
global using Int64Range = SmartAss.Numerics.NumericRange<long>;
global using Int64Ranges = SmartAss.Numerics.NumericRanges<long>;
global using Ints = SmartAss.Inputs<int>;
global using Lines = SmartAss.Inputs<string>;
global using Longs = SmartAss.Inputs<long>;
global using Sequances = SmartAss.Numerics.Sequence;
