global using Advent_of_Code;
global using FluentAssertions;
global using NUnit.Framework;
global using NUnit.Framework.Interfaces;
global using NUnit.Framework.Internal;
global using NUnit.Framework.Internal.Builders;
global using SmartAss;
global using SmartAss.Collections;
global using SmartAss.Diagnostics;
global using SmartAss.Maps;
global using SmartAss.Navigation;
global using SmartAss.Numerics;
global using SmartAss.Parsing;
global using SmartAss.Syntax;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Text.RegularExpressions;
global using CategoryAttribute = Advent_of_Code.CategoryAttribute;
global using Int = System.Numerics.BigInteger;