global using Advent_of_Code;
global using FluentAssertions;
global using NUnit.Framework;
global using NUnit.Framework.Internal;
global using SmartAss;
global using SmartAss.Diagnostics;
global using SmartAss.Numerics;
global using SmartAss.Parsing;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using static System.FormattableString;
global using Int = System.Numerics.BigInteger;
global using CharGrid = SmartAss.Collections.Grid<char>;
global using Ints = SmartAss.Inputs<int>;
global using Longs = SmartAss.Inputs<long>;
global using Lines = SmartAss.Inputs<string>;
